[metadata]
addr = 0x4011e3
size = 0x7b
last_change = 2023-06-19T19:07:57.563246Z

[header]
name = "init_proc"
addr = 0x4011e3
type = "long"

[stack_vars.-0x8]
offset = -8
name = "__saved_rbp"
type = "long"
size = 0x0
addr = 0x4011e3

[stack_vars.0x0]
offset = 0x0
name = "__return_addr"
type = "void* const"
size = 0x0
addr = 0x4011e3
