[metadata]
addr = 0x4017f4
size = 0x8
last_change = 2023-06-19T19:08:00.583959Z

[header]
name = "_fini"
addr = 0x4017f4
type = "long"

[stack_vars.-0x8]
offset = -8
name = "var_8"
type = "void"
size = 0x0
addr = 0x4017f4

[stack_vars.0x0]
offset = 0x0
name = "__return_addr"
type = "void* const"
size = 0x0
addr = 0x4017f4
