[metadata]
addr = 0x4015dd
size = 0x84
last_change = 2023-06-19T19:07:59.048197Z

[header]
name = "rfree"
addr = 0x4015dd
type = "long"

[stack_vars.-0x18]
offset = -24
name = "var_18"
type = "void"
size = 0x0
addr = 0x4015dd

[stack_vars.-0x10]
offset = -16
name = "var_10_1"
type = "long"
size = 0x0
addr = 0x4015dd

[stack_vars.-0x8]
offset = -8
name = "__saved_rbp"
type = "long"
size = 0x0
addr = 0x4015dd

[stack_vars.0x0]
offset = 0x0
name = "__return_addr"
type = "void* const"
size = 0x0
addr = 0x4015dd
