[metadata]
addr = 0x401020
size = 0xb
last_change = 2023-06-19T19:07:42.868957Z

[header]
name = "sub_401020"
addr = 0x401020
type = "long"

[stack_vars.-0x8]
offset = -8
name = "var_8"
type = "long"
size = 0x0
addr = 0x401020

[stack_vars.0x0]
offset = 0x0
name = "__return_addr"
type = "void* const"
size = 0x0
addr = 0x401020
