[metadata]
addr = 0x40149a
size = 0x142
last_change = 2023-06-19T19:07:58.744623Z

[header]
name = "reallocate"
addr = 0x40149a
type = "long"

[stack_vars.-0x28]
offset = -40
name = "var_28"
type = "void"
size = 0x0
addr = 0x40149a

[stack_vars.-0x20]
offset = -32
name = "var_20"
type = "long"
size = 0x0
addr = 0x40149a

[stack_vars.-0x18]
offset = -24
name = "var_18_1"
type = "long"
size = 0x0
addr = 0x40149a

[stack_vars.-0x10]
offset = -16
name = "var_10_1"
type = "long"
size = 0x0
addr = 0x40149a

[stack_vars.-0x8]
offset = -8
name = "__saved_rbp"
type = "long"
size = 0x0
addr = 0x40149a

[stack_vars.0x0]
offset = 0x0
name = "__return_addr"
type = "void* const"
size = 0x0
addr = 0x40149a
