[metadata]
addr = 0x401000
size = 0x16
last_change = 2023-06-19T19:07:41.078638Z

[header]
name = "_init"
addr = 0x401000
type = "void"

[stack_vars.-0x8]
offset = -8
name = "var_8"
type = "void"
size = 0x0
addr = 0x401000

[stack_vars.0x0]
offset = 0x0
name = "__return_addr"
type = "void* const"
size = 0x0
addr = 0x401000
