[metadata]
addr = 0x4011c0
size = 0x1
last_change = 2023-06-19T19:07:56.960649Z

[header]
name = "frame_dummy"
addr = 0x4011c0
type = "void"

[stack_vars.0x0]
offset = 0x0
name = "__return_addr"
type = "void* const"
size = 0x0
addr = 0x4011c0
