[metadata]
addr = 0x4016da
size = 0xa6
last_change = 2023-06-19T19:07:59.664534Z

[header]
name = "main"
addr = 0x4016da
type = "int"

[stack_vars.-0x18]
offset = -24
name = "var_18"
type = "void"
size = 0x0
addr = 0x4016da

[stack_vars.-0x14]
offset = -20
name = "var_14"
type = "int"
size = 0x0
addr = 0x4016da

[stack_vars.-0x10]
offset = -16
name = "var_10"
type = "long"
size = 0x0
addr = 0x4016da

[stack_vars.-0x8]
offset = -8
name = "var_8"
type = "long"
size = 0x0
addr = 0x4016da

[stack_vars.0x0]
offset = 0x0
name = "__return_addr"
type = "void* const"
size = 0x0
addr = 0x4016da

[header.args.0]
offset = 0x0
name = "argc"
type = "int"
size = 0x4

[header.args.1]
offset = 0x1
name = "argv"
type = "char**"
size = 0x8

[header.args.2]
offset = 0x2
name = "envp"
type = "char**"
size = 0x8
