[metadata]
addr = 0x401120
size = 0x20
last_change = 2023-06-19T19:07:49.880991Z

[header]
name = "deregister_tm_clones"
addr = 0x401120
type = "void"

[stack_vars.0x0]
offset = 0x0
name = "__return_addr"
type = "void* const"
size = 0x0
addr = 0x401120
