[metadata]
addr = 0x40125f
size = 0x60
last_change = 2023-06-19T19:07:57.863965Z

[header]
name = "read_long"
addr = 0x40125f
type = "long"

[stack_vars.-0x38]
offset = -56
name = "var_38"
type = "void"
size = 0x0
addr = 0x40125f

[stack_vars.-0x30]
offset = -48
name = "var_30"
type = "long"
size = 0x0
addr = 0x40125f

[stack_vars.-0x28]
offset = -40
name = "var_28"
type = "void"
size = 0x0
addr = 0x40125f

[stack_vars.-0x10]
offset = -16
name = "var_10"
type = "long"
size = 0x0
addr = 0x40125f

[stack_vars.-0x8]
offset = -8
name = "__saved_rbp"
type = "long"
size = 0x0
addr = 0x40125f

[stack_vars.0x0]
offset = 0x0
name = "__return_addr"
type = "void* const"
size = 0x0
addr = 0x40125f
