[metadata]
addr = 0x401662
size = 0x77
last_change = 2023-06-19T19:07:59.360837Z

[header]
name = "menu"
addr = 0x401662
type = "long"

[stack_vars.-0x8]
offset = -8
name = "__saved_rbp"
type = "long"
size = 0x0
addr = 0x401662

[stack_vars.0x0]
offset = 0x0
name = "__return_addr"
type = "void* const"
size = 0x0
addr = 0x401662
