[metadata]
addr = 0x401190
size = 0x20
last_change = 2023-06-19T19:07:53.549542Z

[header]
name = "__do_global_dtors_aux"
addr = 0x401190
type = "void"

[stack_vars.-0x8]
offset = -8
name = "__saved_rbp"
type = "long"
size = 0x0
addr = 0x401190

[stack_vars.0x0]
offset = 0x0
name = "__return_addr"
type = "void* const"
size = 0x0
addr = 0x401190
