[metadata]
addr = 0x401110
size = 0x0
last_change = 2023-06-19T19:07:49.642506Z

[header]
name = "_dl_relocate_static_pie"
addr = 0x401110
type = "long"

[stack_vars.0x0]
offset = 0x0
name = "__return_addr"
type = "void* const"
size = 0x0
addr = 0x401110
