[e_dyn_tag]
last_change = 2023-06-19T19:06:20.180271Z
name = "e_dyn_tag"

[e_dyn_tag.members]
DT_NULL = 0x0
DT_NEEDED = 0x1
DT_PLTRELSZ = 0x2
DT_PLTGOT = 0x3
DT_HASH = 0x4
DT_STRTAB = 0x5
DT_SYMTAB = 0x6
DT_RELA = 0x7
DT_RELASZ = 0x8
DT_RELAENT = 0x9
DT_STRSZ = 0xa
DT_SYMENT = 0xb
DT_INIT = 0xc
DT_FINI = 0xd
DT_SONAME = 0xe
DT_RPATH = 0xf
DT_SYMBOLIC = 0x10
DT_REL = 0x11
DT_RELSZ = 0x12
DT_RELENT = 0x13
DT_PLTREL = 0x14
DT_DEBUG = 0x15
DT_TEXTREL = 0x16
DT_JMPREL = 0x17
DT_BIND_NOW = 0x18
DT_INIT_ARRAY = 0x19
DT_FINI_ARRAY = 0x1a
DT_INIT_ARRAYSZ = 0x1b
DT_FINI_ARRAYSZ = 0x1c
DT_RUNPATH = 0x1d
DT_FLAGS = 0x1e
DT_ENCODING = 0x1f
DT_PREINIT_ARRAY = 0x20
DT_PREINIT_ARRAYSZ = 0x21
DT_LOOS = 0x6000000d
DT_SUNW_RTLDINF = 0x6000000e
DT_HIOS = 0x6ffff000
DT_VALRNGLO = 0x6ffffd00
DT_CHECKSUM = 0x6ffffdf8
DT_PLTPADSZ = 0x6ffffdf9
DT_MOVEENT = 0x6ffffdfa
DT_MOVESZ = 0x6ffffdfb
DT_FEATURE_1 = 0x6ffffdfc
DT_POSFLAG_1 = 0x6ffffdfd
DT_SYMINSZ = 0x6ffffdfe
DT_SYMINENT = 0x6ffffdff
DT_VALRNGHI = 0x6ffffdff
DT_ADDRRNGLO = 0x6ffffe00
DT_GNU_HASH = 0x6ffffef5
DT_CONFIG = 0x6ffffefa
DT_DEPAUDIT = 0x6ffffefb
DT_AUDIT = 0x6ffffefc
DT_PLTPAD = 0x6ffffefd
DT_MOVETAB = 0x6ffffefe
DT_SYMINFO = 0x6ffffeff
DT_ADDRRNGHI = 0x6ffffeff
DT_VERSYM = 0x6ffffff0
DT_RELACOUNT = 0x6ffffff9
DT_RELCOUNT = 0x6ffffffa
DT_FLAGS_1 = 0x6ffffffb
DT_VERDEF = 0x6ffffffc
DT_VERDEFNUM = 0x6ffffffd
DT_VERNEED = 0x6ffffffe
DT_VERNEEDNUM = 0x6fffffff
DT_MIPS_RLD_VERSION = 0x70000001
DT_MIPS_TIME_STAMP = 0x70000002
DT_MIPS_ICHECKSUM = 0x70000003
DT_MIPS_IVERSION = 0x70000004
DT_MIPS_FLAGS = 0x70000005
DT_MIPS_BASE_ADDRESS = 0x70000006
DT_MIPS_CONFLICT = 0x70000008
DT_MIPS_LIBLIST = 0x70000009
DT_MIPS_LOCAL_GOTNO = 0x7000000a
DT_MIPS_CONFLICTNO = 0x7000000b
DT_MIPS_LIBLISTNO = 0x70000010
DT_MIPS_SYMTABNO = 0x70000011
DT_MIPS_UNREFEXTNO = 0x70000012
DT_MIPS_GOTSYM = 0x70000013
DT_MIPS_HIPAGENO = 0x70000014
DT_MIPS_RLD_MAP = 0x70000016
DT_MIPS_RLD_MAP_REL = 0x70000035
