[sh_type]
last_change = 2023-06-19T19:06:22.184374Z
name = "sh_type"

[sh_type.members]
SHT_NULL = 0x0
SHT_PROGBITS = 0x1
SHT_SYMTAB = 0x2
SHT_STRTAB = 0x3
SHT_RELA = 0x4
SHT_HASH = 0x5
SHT_DYNAMIC = 0x6
SHT_NOTE = 0x7
SHT_NOBITS = 0x8
SHT_REL = 0x9
SHT_SHLIB = 0xa
SHT_DYNSYM = 0xb
SHT_AMD64_UNWIND = 0x70000001
SHT_LOUSER = 0x80000000
SHT_HIUSER = 0xffffffff
