[e_machine]
last_change = 2023-06-19T19:06:21.367798Z
name = "e_machine"

[e_machine.members]
EM_NONE = 0x0
EM_M32 = 0x1
EM_SPARC = 0x2
EM_386 = 0x3
EM_68K = 0x4
EM_88K = 0x5
EM_860 = 0x7
EM_MIPS = 0x8
EM_S370 = 0x9
EM_MIPS_RS3_LE = 0xa
EM_PARISC = 0xf
EM_VPP500 = 0x11
EM_SPARC32PLUS = 0x12
EM_960 = 0x13
EM_PPC = 0x14
EM_PPC64 = 0x15
EM_S390 = 0x16
EM_V800 = 0x24
EM_FR20 = 0x25
EM_RH32 = 0x26
EM_RCE = 0x27
EM_ARM = 0x28
EM_FAKE_ALPHA = 0x29
EM_SH = 0x2a
EM_SPARCV9 = 0x2b
EM_TRICORE = 0x2c
EM_ARC = 0x2d
EM_H8_300 = 0x2e
EM_H8_300H = 0x2f
EM_H8S = 0x30
EM_H8_500 = 0x31
EM_IA_64 = 0x32
EM_MIPS_X = 0x33
EM_COLDFIRE = 0x34
EM_68HC12 = 0x35
EM_MMA = 0x36
EM_PCP = 0x37
EM_NCPU = 0x38
EM_NDR1 = 0x39
EM_STARCORE = 0x3a
EM_ME16 = 0x3b
EM_ST100 = 0x3c
EM_TINYJ = 0x3d
EM_X86_64 = 0x3e
EM_PDSP = 0x3f
EM_FX66 = 0x42
EM_ST9PLUS = 0x43
EM_ST7 = 0x44
EM_68HC16 = 0x45
EM_68HC11 = 0x46
EM_68HC08 = 0x47
EM_68HC05 = 0x48
EM_SVX = 0x49
EM_ST19 = 0x4a
EM_VAX = 0x4b
EM_CRIS = 0x4c
EM_JAVELIN = 0x4d
EM_FIREPATH = 0x4e
EM_ZSP = 0x4f
EM_MMIX = 0x50
EM_HUANY = 0x51
EM_PRISM = 0x52
EM_AVR = 0x53
EM_FR30 = 0x54
EM_D10V = 0x55
EM_D30V = 0x56
EM_V850 = 0x57
EM_M32R = 0x58
EM_MN10300 = 0x59
EM_MN10200 = 0x5a
EM_PJ = 0x5b
EM_OPENRISC = 0x5c
EM_ARC_A5 = 0x5d
EM_XTENSA = 0x5e
EM_ALTERA_NIOS2 = 0x71
EM_AARCH64 = 0xb7
EM_TILEPRO = 0xbc
EM_MICROBLAZE = 0xbd
EM_TILEGX = 0xbf
EM_NUM = 0xc0
