[0x4040d0]
last_change = 2023-06-19T19:07:28.314739Z
addr = 0x4040d0
name = "<ExternalSymbol: "__libc_start_main" @ 0x4040d0>"
type = "void(int (* main)(int argc, char** argv, char** envp), int argc, char** ubp_av, void (* init)(), void (* fini)(), void (* rtld_fini)(), void* stack_end) __noreturn"
size = 0x0
