[metadata]
name = "_IO_lock_t"
size = 0x10
last_change = 2023-06-19T19:06:23.794050Z

[members.0x0]
name = "lock"
offset = 0x0
type = "int"
size = 0x4

[members.0x4]
name = "cnt"
offset = 0x4
type = "int"
size = 0x4

[members.0x8]
name = "owner"
offset = 0x8
type = "void*"
size = 0x8
